from .base import DomainError

class UserEmailIsIncorrect(DomainError): ...

class WeakPasswordError(DomainError): ...

class PasswordMismatchError(DomainError): ...

class InvalidCredentials(DomainError): ...

class UserIsAlreadyActiveError(DomainError): ...

class UserIsNotActiveError(DomainError): ...

class UnauthorizedError(DomainError): ...